/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SistemaMedico;

import Connection.PessoaDAO;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Luan Medeiros
 */
public class TelaLogin extends javax.swing.JFrame {

    /** Creates new form TelaLogin */
    public TelaLogin() {
        initComponents();
        PainelNovoCadastro.setVisible(false);
        TelaRecepcionista.setVisible(false);
        TelaProfissional.setVisible(false);
        try {
            cadNovoTelefone.setFormatterFactory(new DefaultFormatterFactory(
                    new MaskFormatter("(##) ####-#####")));
            
             cadNovoCPF.setFormatterFactory(new DefaultFormatterFactory(
                    new MaskFormatter("###.###.###-##")));
             
             cadNovoRG.setFormatterFactory(new DefaultFormatterFactory(
                    new MaskFormatter("###.###.###")));       
             
        } catch (Exception ex) {
            Logger.getLogger(Teste.class.getName()).log(Level.SEVERE, null, ex);
        }

     
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    public void escondeTodosPaineis()
    {
        PainelLogin.setVisible(false);
        PainelNovoCadastro.setVisible(false);
        TelaRecepcionista.setVisible(false);
        TelaProfissional.setVisible(false);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoProfissionais = new javax.swing.ButtonGroup();
        sexo = new javax.swing.ButtonGroup();
        PainelLogin = new javax.swing.JPanel();
        novoCadastro = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        logar = new javax.swing.JButton();
        matricula = new javax.swing.JTextField();
        senha = new javax.swing.JPasswordField();
        PainelNovoCadastro = new javax.swing.JPanel();
        cadNovoNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cadNovoEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cadNovoEndereco = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        radioMedico = new javax.swing.JRadioButton();
        radioOdontologo = new javax.swing.JRadioButton();
        radioNutricionista = new javax.swing.JRadioButton();
        numeroConselho = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cadastrarNovoProfissional = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        cadNovoCPF = new javax.swing.JFormattedTextField();
        cadNovoRG = new javax.swing.JFormattedTextField();
        cadNovoTelefone = new javax.swing.JFormattedTextField();
        cadNovoSenha = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        TelaRecepcionista = new javax.swing.JPanel();
        Tabs = new javax.swing.JTabbedPane();
        Paciente = new javax.swing.JPanel();
        labelNome = new javax.swing.JLabel();
        nome1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        pacienteRG = new javax.swing.JTextField();
        pacienteCPF = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        pacienteEmail = new javax.swing.JTextField();
        pacienteEndereco = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        pacienteTelefone = new javax.swing.JTextField();
        cpf4 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        Prontuario = new javax.swing.JPanel();
        PainelNovoCadastro1 = new javax.swing.JPanel();
        prontIDPessoa = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        prontIdade = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        radioMasculino = new javax.swing.JRadioButton();
        radioFeminino = new javax.swing.JRadioButton();
        jLabel28 = new javax.swing.JLabel();
        cadastrarProfissional1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        prontObservacoes = new javax.swing.JTextArea();
        Agendamento = new javax.swing.JPanel();
        agendHoraCulta = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        agendDataConsulta = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        agendCadastrar = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        agendIDPessoa = new javax.swing.JTextField();
        Emergência = new javax.swing.JPanel();
        emergIDPessoa = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        emergHoraConsulta = new javax.swing.JTextField();
        emergDataConsulta = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        emergCadastrar = new javax.swing.JButton();
        TelaProfissional = new javax.swing.JPanel();
        Tabs1 = new javax.swing.JTabbedPane();
        Paciente1 = new javax.swing.JPanel();
        labelNome1 = new javax.swing.JLabel();
        nome2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        rg2 = new javax.swing.JTextField();
        cpf2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        email1 = new javax.swing.JTextField();
        endereco2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Prontuario1 = new javax.swing.JPanel();
        Agendamento1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        TITTULO = new javax.swing.JLabel();
        Emergência1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        novoCadastro.setText("NOVO CADASTRO");
        novoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoCadastroActionPerformed(evt);
            }
        });

        jLabel2.setText("SENHA");

        jLabel1.setText("MATRÍCULA");

        logar.setText("LOGAR");
        logar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logarActionPerformed(evt);
            }
        });

        matricula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        matricula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        matricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matriculaActionPerformed(evt);
            }
        });
        matricula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                matriculaKeyReleased(evt);
            }
        });

        senha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        senha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout PainelLoginLayout = new javax.swing.GroupLayout(PainelLogin);
        PainelLogin.setLayout(PainelLoginLayout);
        PainelLoginLayout.setHorizontalGroup(
            PainelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLoginLayout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addGroup(PainelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(novoCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(logar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(matricula)
                    .addComponent(senha))
                .addContainerGap(276, Short.MAX_VALUE))
        );
        PainelLoginLayout.setVerticalGroup(
            PainelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLoginLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(PainelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(senha, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(novoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(298, Short.MAX_VALUE))
        );

        cadNovoNome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cadNovoNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cadNovoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadNovoNomeActionPerformed(evt);
            }
        });

        jLabel3.setText("NOME");

        jLabel4.setText("RG");

        jLabel5.setText("EMAIL");

        cadNovoEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cadNovoEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setText("CPF");

        jLabel7.setText("TELEFONE");

        cadNovoEndereco.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cadNovoEndereco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setText("ENDEREÇO");

        grupoProfissionais.add(radioMedico);
        radioMedico.setText("CLÍNICO GERAL");

        grupoProfissionais.add(radioOdontologo);
        radioOdontologo.setText("ODONTÓLOGO");

        grupoProfissionais.add(radioNutricionista);
        radioNutricionista.setText("NUTRICIONISTA");
        radioNutricionista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNutricionistaActionPerformed(evt);
            }
        });

        numeroConselho.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numeroConselho.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        numeroConselho.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                numeroConselhoKeyReleased(evt);
            }
        });

        jLabel9.setText("N° DO CONSELHO");

        cadastrarNovoProfissional.setText("CADASTRAR");
        cadastrarNovoProfissional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarNovoProfissionalActionPerformed(evt);
            }
        });

        jButton3.setText("VOLTAR AO INÍCIO");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        cadNovoCPF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cadNovoCPF.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cadNovoRG.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cadNovoRG.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cadNovoTelefone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cadNovoTelefone.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cadNovoSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cadNovoSenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setText("SENHA");

        javax.swing.GroupLayout PainelNovoCadastroLayout = new javax.swing.GroupLayout(PainelNovoCadastro);
        PainelNovoCadastro.setLayout(PainelNovoCadastroLayout);
        PainelNovoCadastroLayout.setHorizontalGroup(
            PainelNovoCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelNovoCadastroLayout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addGroup(PainelNovoCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelNovoCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(PainelNovoCadastroLayout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cadNovoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PainelNovoCadastroLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cadNovoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PainelNovoCadastroLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cadNovoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PainelNovoCadastroLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cadNovoRG, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PainelNovoCadastroLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cadNovoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PainelNovoCadastroLayout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cadNovoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PainelNovoCadastroLayout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(numeroConselho, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PainelNovoCadastroLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addGroup(PainelNovoCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelNovoCadastroLayout.createSequentialGroup()
                                .addComponent(radioMedico)
                                .addGap(10, 10, 10)
                                .addComponent(radioOdontologo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radioNutricionista))
                            .addGroup(PainelNovoCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cadastrarNovoProfissional, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cadNovoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        PainelNovoCadastroLayout.setVerticalGroup(
            PainelNovoCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelNovoCadastroLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(PainelNovoCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadNovoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelNovoCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cadNovoRG, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addGroup(PainelNovoCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelNovoCadastroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelNovoCadastroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cadNovoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(PainelNovoCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadNovoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelNovoCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadNovoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelNovoCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadNovoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelNovoCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroConselho, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelNovoCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadNovoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelNovoCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioMedico)
                    .addComponent(radioOdontologo)
                    .addComponent(radioNutricionista))
                .addGap(18, 18, 18)
                .addComponent(cadastrarNovoProfissional, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154))
        );

        labelNome.setText("NOME:");

        nome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome1ActionPerformed(evt);
            }
        });

        jLabel12.setText("RG");

        pacienteRG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacienteRGActionPerformed(evt);
            }
        });

        pacienteCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacienteCPFActionPerformed(evt);
            }
        });

        jLabel13.setText("CPF");

        jLabel14.setText("EMAIL");

        pacienteEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacienteEmailActionPerformed(evt);
            }
        });

        pacienteEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacienteEnderecoActionPerformed(evt);
            }
        });

        jLabel15.setText("ENDEREÇO");

        jButton1.setText("REGISTRAR PESSOA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel30.setText("TELEFONE");

        pacienteTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacienteTelefoneActionPerformed(evt);
            }
        });

        cpf4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpf4ActionPerformed(evt);
            }
        });

        jLabel31.setText("MATRÍCULA");

        javax.swing.GroupLayout PacienteLayout = new javax.swing.GroupLayout(Paciente);
        Paciente.setLayout(PacienteLayout);
        PacienteLayout.setHorizontalGroup(
            PacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PacienteLayout.createSequentialGroup()
                        .addComponent(labelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nome1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PacienteLayout.createSequentialGroup()
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cpf4))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PacienteLayout.createSequentialGroup()
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pacienteTelefone))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PacienteLayout.createSequentialGroup()
                            .addGroup(PacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(PacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pacienteEndereco)
                                .addComponent(pacienteEmail)
                                .addComponent(pacienteCPF)
                                .addComponent(pacienteRG, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(254, Short.MAX_VALUE))
        );
        PacienteLayout.setVerticalGroup(
            PacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PacienteLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(PacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pacienteRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pacienteCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pacienteEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(PacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pacienteEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(PacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pacienteTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpf4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jButton1)
                .addContainerGap(197, Short.MAX_VALUE))
        );

        Tabs.addTab("Cadastrar Paciente", Paciente);

        prontIDPessoa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        prontIDPessoa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        prontIDPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prontIDPessoaActionPerformed(evt);
            }
        });

        jLabel20.setText("ID PESSOA");

        jLabel21.setText("IDADE");

        prontIdade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        prontIdade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel23.setText("OBSERVAÇÕES");

        sexo.add(radioMasculino);
        radioMasculino.setText("MASCULINO");

        sexo.add(radioFeminino);
        radioFeminino.setText("FEMININO");

        jLabel28.setText("SEXO");

        cadastrarProfissional1.setText("CADASTRAR");

        prontObservacoes.setColumns(20);
        prontObservacoes.setLineWrap(true);
        prontObservacoes.setRows(5);
        jScrollPane2.setViewportView(prontObservacoes);

        javax.swing.GroupLayout PainelNovoCadastro1Layout = new javax.swing.GroupLayout(PainelNovoCadastro1);
        PainelNovoCadastro1.setLayout(PainelNovoCadastro1Layout);
        PainelNovoCadastro1Layout.setHorizontalGroup(
            PainelNovoCadastro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelNovoCadastro1Layout.createSequentialGroup()
                .addGroup(PainelNovoCadastro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelNovoCadastro1Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(PainelNovoCadastro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PainelNovoCadastro1Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(prontIDPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PainelNovoCadastro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(PainelNovoCadastro1Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel28)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(radioMasculino)
                                    .addGap(10, 10, 10)
                                    .addComponent(radioFeminino))
                                .addGroup(PainelNovoCadastro1Layout.createSequentialGroup()
                                    .addComponent(jLabel21)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(prontIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(PainelNovoCadastro1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(PainelNovoCadastro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PainelNovoCadastro1Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cadastrarProfissional1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        PainelNovoCadastro1Layout.setVerticalGroup(
            PainelNovoCadastro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelNovoCadastro1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(PainelNovoCadastro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prontIDPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelNovoCadastro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prontIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelNovoCadastro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(radioMasculino)
                    .addComponent(radioFeminino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelNovoCadastro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cadastrarProfissional1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ProntuarioLayout = new javax.swing.GroupLayout(Prontuario);
        Prontuario.setLayout(ProntuarioLayout);
        ProntuarioLayout.setHorizontalGroup(
            ProntuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 614, Short.MAX_VALUE)
            .addGroup(ProntuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ProntuarioLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PainelNovoCadastro1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        ProntuarioLayout.setVerticalGroup(
            ProntuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
            .addGroup(ProntuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ProntuarioLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PainelNovoCadastro1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        Tabs.addTab("Prontuario", Prontuario);

        agendHoraCulta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        agendHoraCulta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        agendHoraCulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendHoraCultaActionPerformed(evt);
            }
        });

        jLabel22.setText("HORA CONSULTA");

        agendDataConsulta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        agendDataConsulta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel24.setText("DATA CONSULTA");

        agendCadastrar.setText("CADASTRAR");

        jLabel25.setText("ID PESSOA");

        agendIDPessoa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        agendIDPessoa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        agendIDPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendIDPessoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AgendamentoLayout = new javax.swing.GroupLayout(Agendamento);
        Agendamento.setLayout(AgendamentoLayout);
        AgendamentoLayout.setHorizontalGroup(
            AgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AgendamentoLayout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(AgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel25)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agendCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agendIDPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agendHoraCulta, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agendDataConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(117, 117, 117))
        );
        AgendamentoLayout.setVerticalGroup(
            AgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgendamentoLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(AgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agendIDPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(agendHoraCulta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agendDataConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(agendCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(296, Short.MAX_VALUE))
        );

        Tabs.addTab("Agendamento", Agendamento);

        emergIDPessoa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        emergIDPessoa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        emergIDPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emergIDPessoaActionPerformed(evt);
            }
        });

        jLabel26.setText("ID PESSOA");

        jLabel27.setText("HORA CONSULTA");

        emergHoraConsulta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        emergHoraConsulta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        emergHoraConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emergHoraConsultaActionPerformed(evt);
            }
        });

        emergDataConsulta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        emergDataConsulta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel29.setText("DATA CONSULTA");

        emergCadastrar.setText("CADATRAR");

        javax.swing.GroupLayout EmergênciaLayout = new javax.swing.GroupLayout(Emergência);
        Emergência.setLayout(EmergênciaLayout);
        EmergênciaLayout.setHorizontalGroup(
            EmergênciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmergênciaLayout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(EmergênciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel27)
                    .addComponent(jLabel26)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EmergênciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emergCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emergIDPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emergHoraConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emergDataConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(117, 117, 117))
        );
        EmergênciaLayout.setVerticalGroup(
            EmergênciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmergênciaLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(EmergênciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emergIDPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EmergênciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(emergHoraConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EmergênciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emergDataConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emergCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(296, Short.MAX_VALUE))
        );

        Tabs.addTab("Emergência", Emergência);

        javax.swing.GroupLayout TelaRecepcionistaLayout = new javax.swing.GroupLayout(TelaRecepcionista);
        TelaRecepcionista.setLayout(TelaRecepcionistaLayout);
        TelaRecepcionistaLayout.setHorizontalGroup(
            TelaRecepcionistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 742, Short.MAX_VALUE)
            .addGroup(TelaRecepcionistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(TelaRecepcionistaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        TelaRecepcionistaLayout.setVerticalGroup(
            TelaRecepcionistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 545, Short.MAX_VALUE)
            .addGroup(TelaRecepcionistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(TelaRecepcionistaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        labelNome1.setText("NOME:");

        nome2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome2ActionPerformed(evt);
            }
        });

        jLabel16.setText("RG");

        rg2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rg2ActionPerformed(evt);
            }
        });

        cpf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpf2ActionPerformed(evt);
            }
        });

        jLabel17.setText("CPF");

        jLabel18.setText("EMAIL");

        email1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email1ActionPerformed(evt);
            }
        });

        endereco2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endereco2ActionPerformed(evt);
            }
        });

        jLabel19.setText("ENDEREÇO");

        jButton2.setText("REGISTRAR PESSOA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Paciente1Layout = new javax.swing.GroupLayout(Paciente1);
        Paciente1.setLayout(Paciente1Layout);
        Paciente1Layout.setHorizontalGroup(
            Paciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Paciente1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Paciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Paciente1Layout.createSequentialGroup()
                        .addComponent(labelNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nome2, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Paciente1Layout.createSequentialGroup()
                        .addGroup(Paciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Paciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(endereco2)
                            .addComponent(email1)
                            .addComponent(cpf2)
                            .addComponent(rg2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(254, Short.MAX_VALUE))
        );
        Paciente1Layout.setVerticalGroup(
            Paciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Paciente1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(Paciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nome2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Paciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Paciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Paciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(Paciente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endereco2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jButton2)
                .addContainerGap(265, Short.MAX_VALUE))
        );

        Tabs1.addTab("Cadastrar Paciente", Paciente1);

        javax.swing.GroupLayout Prontuario1Layout = new javax.swing.GroupLayout(Prontuario1);
        Prontuario1.setLayout(Prontuario1Layout);
        Prontuario1Layout.setHorizontalGroup(
            Prontuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 614, Short.MAX_VALUE)
        );
        Prontuario1Layout.setVerticalGroup(
            Prontuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        Tabs1.addTab("Prontuario", Prontuario1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PACIENTE", "HORÁRIO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        TITTULO.setText("ATENDIMENTOS DE HOJE");

        javax.swing.GroupLayout Agendamento1Layout = new javax.swing.GroupLayout(Agendamento1);
        Agendamento1.setLayout(Agendamento1Layout);
        Agendamento1Layout.setHorizontalGroup(
            Agendamento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Agendamento1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Agendamento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TITTULO, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        Agendamento1Layout.setVerticalGroup(
            Agendamento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Agendamento1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(TITTULO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        Tabs1.addTab("Agendamento", Agendamento1);

        javax.swing.GroupLayout Emergência1Layout = new javax.swing.GroupLayout(Emergência1);
        Emergência1.setLayout(Emergência1Layout);
        Emergência1Layout.setHorizontalGroup(
            Emergência1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 614, Short.MAX_VALUE)
        );
        Emergência1Layout.setVerticalGroup(
            Emergência1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        Tabs1.addTab("Emergência", Emergência1);

        javax.swing.GroupLayout TelaProfissionalLayout = new javax.swing.GroupLayout(TelaProfissional);
        TelaProfissional.setLayout(TelaProfissionalLayout);
        TelaProfissionalLayout.setHorizontalGroup(
            TelaProfissionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 742, Short.MAX_VALUE)
            .addGroup(TelaProfissionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(TelaProfissionalLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Tabs1, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        TelaProfissionalLayout.setVerticalGroup(
            TelaProfissionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 545, Short.MAX_VALUE)
            .addGroup(TelaProfissionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(TelaProfissionalLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Tabs1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PainelNovoCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(TelaRecepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(37, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(TelaProfissional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(37, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PainelNovoCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(TelaRecepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(26, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(TelaProfissional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadNovoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadNovoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadNovoNomeActionPerformed

    private void radioNutricionistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNutricionistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioNutricionistaActionPerformed

    private void novoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoCadastroActionPerformed
        escondeTodosPaineis();
        PainelNovoCadastro.setVisible(true);
    }//GEN-LAST:event_novoCadastroActionPerformed

    private void nome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome1ActionPerformed

    private void pacienteRGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacienteRGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pacienteRGActionPerformed

    private void pacienteCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacienteCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pacienteCPFActionPerformed

    private void pacienteEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacienteEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pacienteEmailActionPerformed

    private void pacienteEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacienteEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pacienteEnderecoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Pessoa pes = new Pessoa();
        //matricula,rg,cpf,email,nome,endereco
        pes.setCpf(pacienteCPF.getText()+"");
        pes.setRg(pacienteRG.getText()+"");
        pes.setEndereco(pacienteEndereco.getText()+"");
        pes.setMatricula(pacienteCPF.getText()+"");
        pes.setNome(pacienteCPF.getText()+"");
        pes.setEmail(pacienteEmail.getText()+"");
        pes.setTelefone(pacienteTelefone.getText()+"");
        
                       
        //matricula,rg,cpf,email,nome,endereco

//            PessoaDAO.criarPessoa(pes);


    }//GEN-LAST:event_jButton1ActionPerformed

    private void nome2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome2ActionPerformed

    private void rg2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rg2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rg2ActionPerformed

    private void cpf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpf2ActionPerformed

    private void email1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email1ActionPerformed

    private void endereco2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endereco2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endereco2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void prontIDPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prontIDPessoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prontIDPessoaActionPerformed

    private void agendHoraCultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendHoraCultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agendHoraCultaActionPerformed

    private void agendIDPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendIDPessoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agendIDPessoaActionPerformed

    private void emergIDPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emergIDPessoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emergIDPessoaActionPerformed

    private void emergHoraConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emergHoraConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emergHoraConsultaActionPerformed

    private void pacienteTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacienteTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pacienteTelefoneActionPerformed

    private void cpf4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpf4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpf4ActionPerformed

    private void logarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logarActionPerformed
        PessoaDAO pessoaDAO = new PessoaDAO();
        Pessoa pes =  new Pessoa();
        pes.setSenha(senha.getText());
        pes.setId_pessoa(Integer.parseInt(matricula.getText()));
        System.out.println("LOGIN E SENHA: "+pes.getId_pessoa()+" - - "+pes.getSenha());
        //pes.setId_pessoa(Integer.parseInt(matricula.getText().replaceAll("[^0123456789]", "")));
        if(matricula.getText().length() > 0 && senha.getText().length() > 0 )
        {
            if(pessoaDAO.loginProfissional(pes)==true)
            {
                escondeTodosPaineis();
                TelaProfissional.setVisible(true);            
            }
            else if(pessoaDAO.loginRecepcionista(pes)==true)
            {
                escondeTodosPaineis();
                TelaRecepcionista.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Usuário inexistente ou dados errados!");        
            }
        }        
    }//GEN-LAST:event_logarActionPerformed

    private void matriculaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_matriculaKeyReleased
                matricula.setText(matricula.getText().replaceAll("[^0123456789]", ""));
        if (matricula.getText().length() > 16) {
           matricula.setText(matricula.getText().substring (0, 16));
            }
    }//GEN-LAST:event_matriculaKeyReleased

    private void cadastrarNovoProfissionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarNovoProfissionalActionPerformed
        PessoaDAO pessoaDAO = new PessoaDAO();
        if(cadNovoNome.getText().length() > 0 &&
           cadNovoRG.getText().replaceAll("[^0123456789]", "").length() > 0 &&
           cadNovoEndereco.getText().length() > 0 &&
           cadNovoTelefone.getText().replaceAll("[^0123456789]", "").length() > 0 &&
           numeroConselho.getText().length() > 0 &&                                         
           cadNovoCPF.getText().replaceAll("[^0123456789]", "").length() > 0 &&
           cadNovoSenha.getText().length() > 0 &&     
           cadNovoEmail.getText().length() > 0 &&
                (radioMedico.isSelected() || radioOdontologo.isSelected() || radioNutricionista.isSelected()))                            
          {
                Pessoa pessoa = new Pessoa(1, cadNovoNome.getText(), cadNovoRG.getText().replaceAll("[^0123456789]", ""), cadNovoCPF.getText().replaceAll("[^0123456789]", ""), cadNovoEmail.getText(), cadNovoEndereco.getText(), cadNovoTelefone.getText().replaceAll("[^0123456789]", ""),cadNovoSenha.getText(), numeroConselho.getText());
                if(radioMedico.isSelected())
                {
                    pessoaDAO.criarMedico(pessoa);
                }
                else if(radioOdontologo.isSelected())
                {
                    pessoaDAO.criarDentista(pessoa);
                }
                else if(radioNutricionista.isSelected())
                {
                    pessoaDAO.criarNutricionista(pessoa);
                }
            
            
       /* if(PessoaDAO.login(pes)==true)
        {*/
            
            
       /* }else{
            JOptionPane.showMessageDialog(null, "Usuário inixestinte ou dados errados!");
        }*/
        }
        else
        {
            JOptionPane.showMessageDialog(null, "TODOS OS CAMPOS DEVEM SER PREENCHIDOS!");
        }
    }//GEN-LAST:event_cadastrarNovoProfissionalActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        escondeTodosPaineis();
        PainelLogin.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void numeroConselhoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroConselhoKeyReleased
        numeroConselho.setText(numeroConselho.getText().replaceAll("[^0123456789]", ""));
    }//GEN-LAST:event_numeroConselhoKeyReleased

    private void matriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matriculaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Agendamento;
    private javax.swing.JPanel Agendamento1;
    private javax.swing.JPanel Emergência;
    private javax.swing.JPanel Emergência1;
    private javax.swing.JPanel Paciente;
    private javax.swing.JPanel Paciente1;
    private javax.swing.JPanel PainelLogin;
    private javax.swing.JPanel PainelNovoCadastro;
    private javax.swing.JPanel PainelNovoCadastro1;
    private javax.swing.JPanel Prontuario;
    private javax.swing.JPanel Prontuario1;
    private javax.swing.JLabel TITTULO;
    private javax.swing.JTabbedPane Tabs;
    private javax.swing.JTabbedPane Tabs1;
    private javax.swing.JPanel TelaProfissional;
    private javax.swing.JPanel TelaRecepcionista;
    private javax.swing.JButton agendCadastrar;
    private javax.swing.JTextField agendDataConsulta;
    private javax.swing.JTextField agendHoraCulta;
    private javax.swing.JTextField agendIDPessoa;
    private javax.swing.JFormattedTextField cadNovoCPF;
    private javax.swing.JTextField cadNovoEmail;
    private javax.swing.JTextField cadNovoEndereco;
    private javax.swing.JTextField cadNovoNome;
    private javax.swing.JFormattedTextField cadNovoRG;
    private javax.swing.JPasswordField cadNovoSenha;
    private javax.swing.JFormattedTextField cadNovoTelefone;
    private javax.swing.JButton cadastrarNovoProfissional;
    private javax.swing.JButton cadastrarProfissional1;
    private javax.swing.JTextField cpf2;
    private javax.swing.JTextField cpf4;
    private javax.swing.JTextField email1;
    private javax.swing.JButton emergCadastrar;
    private javax.swing.JTextField emergDataConsulta;
    private javax.swing.JTextField emergHoraConsulta;
    private javax.swing.JTextField emergIDPessoa;
    private javax.swing.JTextField endereco2;
    private javax.swing.ButtonGroup grupoProfissionais;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelNome1;
    private javax.swing.JButton logar;
    private javax.swing.JTextField matricula;
    private javax.swing.JTextField nome1;
    private javax.swing.JTextField nome2;
    private javax.swing.JButton novoCadastro;
    private javax.swing.JTextField numeroConselho;
    private javax.swing.JTextField pacienteCPF;
    private javax.swing.JTextField pacienteEmail;
    private javax.swing.JTextField pacienteEndereco;
    private javax.swing.JTextField pacienteRG;
    private javax.swing.JTextField pacienteTelefone;
    private javax.swing.JTextField prontIDPessoa;
    private javax.swing.JTextField prontIdade;
    private javax.swing.JTextArea prontObservacoes;
    private javax.swing.JRadioButton radioFeminino;
    private javax.swing.JRadioButton radioMasculino;
    private javax.swing.JRadioButton radioMedico;
    private javax.swing.JRadioButton radioNutricionista;
    private javax.swing.JRadioButton radioOdontologo;
    private javax.swing.JTextField rg2;
    private javax.swing.JPasswordField senha;
    private javax.swing.ButtonGroup sexo;
    // End of variables declaration//GEN-END:variables
}
